
apiVersion: apps/v1
kind: Deployment
metadata:
 name: order-ms 
spec:
 replicas: 3
 selector:
   matchLabels:
    app: payments-ms
 template:
  metadata:
   labels:
    app: payments-ms
  spec:  
   containers:
    - name: payments-ms
      image: pseshagiri/microservices:payments-ms-2
      imagePullPolicy: Always
      ports:
       - containerPort: 9003
      livenessProbe:
       httpGet:
        path: /payments
        port: 9003
        httpHeaders:
         - name: Custom-Header
           value: Awesome
       initialDelaySeconds: 3
       periodSeconds: 3         

# service type loadbalance
---

apiVersion: v1
kind: Service
metadata:
 name: payments-ms
 labels:
  app: payments-ms
  k8s: payments-ms
spec:
 selector:
  app: payments-ms
 ports:
  - name: http
    port: 9003
    protocol: TCP
    targetPort: 9003 
 type: LoadBalancer
   
 
       
   
