server:
 port: 9003
spring:
 application:
  name: payments-ms
 datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/fruitsretaildb
  username: postgres
  password: HpEcbMnCjs