server:
 port: 9003
spring:
 application:
  name: payments-ms
 datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/retails
  username: root
  password: Seshagiri#21
